version: '3'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=car_rental
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Baza123
      - ALLOW_IP_RANGE-0.0.0.0/0
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/db/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
    - "5432:5432"
